### ISSUE TITLE
ERROR: Could not detect Ninja v1.8.2 or newer

### ISSUE THREAD

**Issue by yapinm** [MiSTeX-devel/MiSTeX-ports#15]
**Problem:**
ninja is not installed in venv.

**Log:**
--- SNIP --
Configuring picolibc.h using configuration
Build targets in project: 9
NOTICE: Future-deprecated features used:
 * 0.56.0: {'meson.source_root'}
 * 0.58.0: {'meson.get_cross_property'}

picolibc 1.7.9

  User defined options
    Cross files         : cross.txt
    includedir          : picolibc/riscv64-unknown-elf/include
    libdir              : picolibc/riscv64-unknown-elf/lib
    atomic-ungetc       : false
    format-default      : integer
    io-long-long        : true
    multilib            : false
    picocrt             : false
    thread-local-storage: false

ERROR: Could not detect Ninja v1.8.2 or newer

A full log can be found at /home/dev/Code/MiSTeX-devel/MiSTeX-boards/build/qmtech_ep4cgx150_mistex/Menu/software/libc/meson-logs/meson-log.txt
make: *** [/home/dev/Code/MiSTeX-devel/MiSTeX-boards/venv/lib/python3.10/site-packages/litex/soc/software/libc/Makefile:43: __libc.a] Error 1
make: Leaving directory '/home/dev/Code/MiSTeX-devel/MiSTeX-boards/build/qmtech_ep4cgx150_mistex/Menu/software/libc'
Traceback (most recent call last):
  File "/home/dev/Code/MiSTeX-devel/MiSTeX-boards/mistex_boards/qmtech_ep4cgx150_mistex.py", line 297, in <module>
    handle_main(main)
  File "/home/dev/Code/MiSTeX-devel/MiSTeX-boards/mistex_boards/util.py", line 183, in handle_main
    main(coredir, core)
  File "/home/dev/Code/MiSTeX-devel/MiSTeX-boards/mistex_boards/qmtech_ep4cgx150_mistex.py", line 294, in main
    builder.build(build_name = get_build_name(core))
  File "/home/dev/Code/MiSTeX-devel/MiSTeX-boards/venv/lib/python3.10/site-packages/litex/soc/integration/builder.py", line 357, in build
    self._generate_rom_software(compile_bios=use_bios)
  File "/home/dev/Code/MiSTeX-devel/MiSTeX-boards/venv/lib/python3.10/site-packages/litex/soc/integration/builder.py", line 291, in _generate_rom_software
    subprocess.check_call(["make", "-C", dst_dir, "-f", makefile])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '/home/dev/Code/MiSTeX-devel/MiSTeX-boards/build/qmtech_ep4cgx150_mistex/Menu/software/libc', '-f', '/home/dev/Code/MiSTeX-devel/MiSTeX-boards/venv/lib/python3.10/site-packages/litex/soc/software/libc/Makefile']' returned non-zero exit status 2.

**Solution:**
Add ninja to requirements.txt

**Comment by hansfbaier** [comment]
OK done.
